apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: secret-pod
    image: busybox
    command: ["bin/sh", "-c", "echo Hello, $(FIRST_NAME) $(LAST_NAME) and $(BASE_SIX) && sleep 3600"]
    env:
    - name: BASE_SIX
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: base64 
    - name: FIRST_NAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: firstName
    - name: LAST_NAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: lastName
