apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume
  labels:
    volume: data
spec:
  storageClassName: my-storage-class
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/mnt/data"
