apiVersion: v1
kind: Pod
metadata:
  name: my-config-map-pod
spec:
  containers:
  - name: my-config-map-pod
    image: busybox
    command: ["/bin/sh", "-c", "cat mnt/config/config.cfg | grep firstName && sleep 3600"]
    volumeMounts:
    - name: config-volume
      mountPath: "mnt/config"
  volumes:
  - name: config-volume
    configMap:
      name: my-config-map
